language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip3 install -r requirements-test.txt
  - pip3 install -r requirements.txt

script:
  - pycodestyle stlcapsmh/
  - pylint stlcapsmh/

notifications:
  email: false
